### ISSUE TITLE
Unable to do pip install

### ISSUE THREAD

**Issue by vibincwilson** [abmercado19/behavex-images#4]
ERROR: Could not find a version that satisfies the requirement behavex-images (from versions: none)
ERROR: No matching distribution found for behavex-images

**Comment by hrcorval** [comment]
Hi @vibincwilson, this issue has been fixed. We are going wait for your confirmation until we perform a new release, just in case you see it was not fixed accordingly.
Thanks!

**Comment by hrcorval** [comment]
Hi @vibincwilson. The issue has been fixed in release version 3.0.7.
I hope it helps!
