### ISSUE TITLE
Use of numpy deprecated type

### ISSUE THREAD

**Issue by Sergmaster00** [abmercado19/behavex-images#7]
In dhash function, the dtype for the pixels is set to numpy.float, which is deprecated since Numpy 1.20.

Leads to an error message regarding the deprecation. 

Can be fixed by changing to numpy.float64.

**Comment by hrcorval** [comment]
I agree with the changes proposed in the PR. It has been accepted. We will launch a new version next week.

**Comment by hrcorval** [comment]
Hi @Sergmaster00, the changes have been merged and released in behavex-images version 3.0.7.
I hope it helps!
Thanks!
